### ISSUE TITLE
0x12e error in claim asset cross-program invocation

### ISSUE THREAD

**Issue by halimabergaoui** [QuarryProtocol/quarry#146]
Hey, 
 I tried redeploying this program and using it in a cross-program invocation but I kept getting this error in the claim reward function.
![telegram-cloud-photo-size-4-6021513616525735756-y](https://user-images.githubusercontent.com/16075710/138291751-7a17924b-904e-4339-aca0-06018806c1db.jpg)
Do you have any idea about the cause of this error?

**Comment by michaelhly** [comment]
> > Could be this error, where you did not provide enough allowance to your minter:
> > https://github.com/QuarryProtocol/quarry/blob/b7ca7bb73332311822600c535dc360c338edb17d/programs/quarry-mint-wrapper/src/lib.rs#L491
> 
> I don't see this msg in my error log and I already tried giving it allowance but the issue persisted.

Can you post your error log?

**Comment by michaelhly** [comment]
How are you deploying quarry? How come you don't have a program that starts with `Q`?

https://github.com/QuarryProtocol/quarry/blob/8fe74eb6cc0b2af158ea56a002de00e454818a29/Anchor.toml#L8

**Comment by halimabergaoui** [comment]
> How are you deploying quarry? How come you don't have a program that starts with `Q`?
> 
> https://github.com/QuarryProtocol/quarry/blob/8fe74eb6cc0b2af158ea56a002de00e454818a29/Anchor.toml#L8

I redeployed the program with different address on devnet 
quarry_mine : ECgnvNxKC1eHDfoDX2Ac6hsPFdCsSJWA4fxVd1SDDtrm

quarry_mint_wrapper : 7fDhLGXxEqZrGD9qAj7887pwuxD6JgRZhb1u533B6yGr

quarry_registry: HBvVFWMXaLobdXvmchPtUcYWerkGN5aWLTsNSWoMqBm9

**Comment by michaelhly** [comment]
> > How are you deploying quarry? How come you don't have a program that starts with `Q`?
> > https://github.com/QuarryProtocol/quarry/blob/8fe74eb6cc0b2af158ea56a002de00e454818a29/Anchor.toml#L8
> 
> I redeployed the program with different address on devnet quarry_mine : ECgnvNxKC1eHDfoDX2Ac6hsPFdCsSJWA4fxVd1SDDtrm
> 
> quarry_mint_wrapper : 7fDhLGXxEqZrGD9qAj7887pwuxD6JgRZhb1u533B6yGr
> 
> quarry_registry: HBvVFWMXaLobdXvmchPtUcYWerkGN5aWLTsNSWoMqBm9

Is `6sGV...` your own program? What program is that? Also, we've deployed the quarry programs onto devnet with these addresses:
https://github.com/QuarryProtocol/quarry/blob/8fe74eb6cc0b2af158ea56a002de00e454818a29/Anchor.toml#L8

https://explorer.solana.com/address/QMNeHCGYnLVDn1icRAfQZpjPLBNkfGbSKRB83G5d8KB?cluster=devnet

**Comment by halimabergaoui** [comment]
> 6sGV

Yes, it is a mock program that only performs a cross-program invocation to quarry functions. So is the problem here is that I redeployed the program and did not use the original Q address?

**Comment by halimabergaoui** [comment]
@michaelhly I tried using the existing Q address and the published crates instead of my local program but I still get the same problem in the claim reward function.

<img width="1092" alt="Screen Shot 2021-11-03 at 8 15 33 AM" src="https://user-images.githubusercontent.com/16075710/140043941-eda158ee-bde0-4d3b-8a08-cfc364c727ff.png">

**Comment by michaelhly** [comment]
> @michaelhly I tried using the existing Q address and the published crates instead of my local program but I still get the same problem in the claim reward function.
> 
> <img alt="Screen Shot 2021-11-03 at 8 15 33 AM" width="1092" src="https://user-images.githubusercontent.com/16075710/140043941-eda158ee-bde0-4d3b-8a08-cfc364c727ff.png">

You've exceeded allowance:
https://github.com/QuarryProtocol/quarry/blob/b7ca7bb73332311822600c535dc360c338edb17d/programs/quarry-mint-wrapper/src/lib.rs#L491

Can you read the allowance on your minter?
https://github.com/QuarryProtocol/quarry/blob/b7ca7bb73332311822600c535dc360c338edb17d/programs/quarry-mint-wrapper/src/lib.rs#L382

**Comment by halimabergaoui** [comment]
> > @michaelhly I tried using the existing Q address and the published crates instead of my local program but I still get the same problem in the claim reward function.
> > <img alt="Screen Shot 2021-11-03 at 8 15 33 AM" width="1092" src="https://user-images.githubusercontent.com/16075710/140043941-eda158ee-bde0-4d3b-8a08-cfc364c727ff.png">
> 
> You've exceeded allowance:
> 
> https://github.com/QuarryProtocol/quarry/blob/b7ca7bb73332311822600c535dc360c338edb17d/programs/quarry-mint-wrapper/src/lib.rs#L491
> 
> Can you read the allowance on your minter?
> 
> https://github.com/QuarryProtocol/quarry/blob/b7ca7bb73332311822600c535dc360c338edb17d/programs/quarry-mint-wrapper/src/lib.rs#L382

Yes, it is as you said the reward is greater than the minter allowance. Thank you @michaelhly  problem solved.
